server:
  port: 8012
spring:
  application:
    name: flash-message
  cache:
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webflashsc?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.126.com
    username: enilu@126.com
    password: NETLKXMXDHHMQWLQ
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enabled: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: info,health,heapdump,beans,trace
info:
  app:
    name: flash-message
    version: 1.0