server:
  port: 8010
spring:
  application:
    name: flash-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuguoqi618/web-flash-spring-cloud.git
          force-pull: true
          search-paths: config
          username: liuguoqi618
          password: q1211321.*
          refresh-rate: 15
          default-label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/